behaviors:
  EdgeRunnerBasic:
    trainer_type: ppo

    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 1.0e-5
      beta: 1.0e-5
      epsilon: 0.05
      lambd: 0.95
      num_epoch: 2
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 10000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 10
    checkpoint_interval: 1000