behaviors:
  EdgeRunnerBasic:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4096
      learning_rate: 1.0e-4
      beta: 2.0e-4
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        gamma: 0.99
        strength: 0.7
        demo_path: Assets/Demonstrations/GapJump.demo

    behavioral_cloning:
      demo_path: Assets/Demonstrations/GapJump.demo
      strength: 0.6
      steps: 120000

    max_steps: 150000
    time_horizon: 64
    summary_freq: 1000
    keep_checkpoints: 10